<a href="https://colab.research.google.com/github/mvajhi/unsupervised-learning/blob/master/HW2/selection%E2%80%AC%E2%80%AC_%E2%80%AB%E2%80%AAforward.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy.optimize as so
import math
from IPython.display import display
import seaborn as sns


In [2]:
df = pd.read_csv('/content/cancer.csv')
df[:5]

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.describe()

id  radius_mean  texture_mean  perimeter_mean    area_mean  \
count  5.690000e+02   569.000000    569.000000      569.000000   569.000000   
mean   3.037183e+07    14.127292     19.289649       91.969033   654.889104   
std    1.250206e+08     3.524049      4.301036       24.298981   351.914129   
min    8.670000e+03     6.981000      9.710000       43.790000   143.500000   
25%    8.692180e+05    11.700000     16.170000       75.170000   420.300000   
50%    9.060240e+05    13.370000     18.840000       86.240000   551.100000   
75%    8.813129e+06    15.780000     21.800000      104.100000   782.700000   
max    9.113205e+08    28.110000     39.280000      188.500000  2501.000000   

       smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       symmetry_mean  ...  texture_worst  perimeter_worst   area_worst  \
count     569.000000  ...     569.000000       569.000000   569.000000   
mean        0.181162  ...      25.677223       107.261213   880.583128   
std         0.027414  ...       6.146258        33.602542   569.356993   
min         0.106000  ...      12.020000        50.410000   185.200000   
25%         0.161900  ...      21.080000        84.110000   515.300000   
50%         0.179200  ...      25.410000        97.660000   686.500000   
75%         0.195700  ...      29.720000       125.400000  1084.000000   
max         0.304000  ...      49.540000       251.200000  4254.000000   

       smoothness_worst  compactness_worst  concavity_worst  \
count        569.000000         569.000000       569.000000   
mean           0.132369           0.254265         0.272188   
std            0.022832           0.157336         0.208624   
min            0.071170           0.027290         0.000000   
25%            0.116600           0.147200         0.114500   
50%            0.131300           0.211900         0.226700   
75%            0.146000           0.339100         0.382900   
max            0.222600           1.058000         1.252000   

       concave points_worst  symmetry_worst  fractal_dimension_worst  \
count            569.000000      569.000000               569.000000   
mean               0.114606        0.290076                 0.083946   
std                0.065732        0.061867                 0.018061   
min                0.000000        0.156500                 0.055040   
25%                0.064930        0.250400                 0.071460   
50%                0.099930        0.282200                 0.080040   
75%                0.161400        0.317900                 0.092080   
max                0.291000        0.663800                 0.207500   

       Unnamed: 32  
count          0.0  
mean           NaN  
std            NaN  
min            NaN  
25%            NaN  
50%            NaN  
75%            NaN  
max            NaN  

[8 rows x 32 columns]

In [4]:
df.shape
# پاسخ بخش ۲

(569, 33)

In [5]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

## Remove outlire

ستون آخر اشتباه و ناقص است آن را حذف می کنیم و همچنین ستون id بی اهمیت است آن را هم حذف می کنیم. همچنین چون در صورت سوال گفته شده داده های پرت را حذف کنیم آن ها را حذف می کنیم در حالت عادی معقول نیست این کارو در حالت کلی انجام بدیم باید علت دادگان پرت را بدانیم و با آگاهی آن ها را حذف کنیم.
می شود داده های پرت را با گزینش خاصی جدا کرد ولی در حالت کلی ۱.۵ طول جعبه در نمودار جعبه ای خارج از جعبه به بعد را داده پرت در نظر می گیرد. ماهم آنها را حذف می کنیم.

In [6]:
df = df.drop(columns=['id', 'Unnamed: 32'])

In [7]:
features = [col for col in df.columns if col != 'diagnosis' and np.issubdtype(df[col].dtype, np.number)]
df_cleaned = df.copy()


inlier_mask = pd.Series(True, index=df.index)
for col in features:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    inlier_mask &= (df[col] >= lower_bound) & (df[col] <= upper_bound)

df_cleaned = df[inlier_mask]
print(np.sum(~inlier_mask))

171


## Classification

In [8]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [9]:
df_cleaned['diagnosis'] = LabelEncoder().fit_transform(df_cleaned['diagnosis'])

X = df_cleaned.drop(columns=['diagnosis'])
y = df_cleaned['diagnosis']

/tmp/ipython-input-9-3547194035.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['diagnosis'] = LabelEncoder().fit_transform(df_cleaned['diagnosis'])


In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [22]:
model = xgb.XGBClassifier()
model.fit(X_train, y_train)

y_pred_train = model.predict(X_train)
y_pred = model.predict(X_test)

accuracy_train = accuracy_score(y_train, y_pred_train)
accuracy_test = accuracy_score(y_test, y_pred)
print("test acc: ", accuracy_train)
print("test acc: ", accuracy_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

test acc:  1.0
test acc:  0.95
[[59  2]
 [ 2 17]]
              precision    recall  f1-score   support

           0       0.97      0.97      0.97        61
           1       0.89      0.89      0.89        19

    accuracy                           0.95        80
   macro avg       0.93      0.93      0.93        80
weighted avg       0.95      0.95      0.95        80



## Feature Selection

In [12]:
from sklearn.feature_selection import SequentialFeatureSelector

In [13]:
MAX_FEATURES = 10

for k in range(1, MAX_FEATURES + 1):
    print("".join(['-']*40))
    print(k)

    sfs = SequentialFeatureSelector(estimator=model,
                                  n_features_to_select=k,
                                  direction='forward')
    sfs.fit(X_train, y_train)


    sf_mask = sfs.get_support()
    sf_names = X_train.columns[sf_mask]
    print(sf_names)

    X_train_sfs = sfs.transform(X_train)
    X_test_sfs = sfs.transform(X_test)

    model_sfs = xgb.XGBClassifier()
    model_sfs.fit(X_train_sfs, y_train)

    y_pred_sfs = model_sfs.predict(X_test_sfs)
    y_pred_train_sfs = model_sfs.predict(X_train_sfs)

    accuracy_train = accuracy_score(y_train, y_pred_train_sfs)
    accuracy_test = accuracy_score(y_test, y_pred_sfs)
    print("train acc: ", accuracy_train)
    print("test acc: ", accuracy_test)
    print(confusion_matrix(y_test, y_pred_sfs))

----------------------------------------
1
Index(['perimeter_worst'], dtype='object')
train acc:  0.9622641509433962
test acc:  0.9
[[53  3]
 [ 5 19]]
----------------------------------------
2
Index(['texture_worst', 'perimeter_worst'], dtype='object')
train acc:  0.9968553459119497
test acc:  0.9125
[[53  3]
 [ 4 20]]
----------------------------------------
3
Index(['compactness_se', 'texture_worst', 'perimeter_worst'], dtype='object')
train acc:  0.9968553459119497
test acc:  0.9125
[[53  3]
 [ 4 20]]
----------------------------------------
4
Index(['texture_mean', 'compactness_se', 'texture_worst', 'perimeter_worst'], dtype='object')
train acc:  1.0
test acc:  0.9
[[53  3]
 [ 5 19]]
----------------------------------------
5
Index(['texture_mean', 'concave points_mean', 'compactness_se',
       'texture_worst', 'perimeter_worst'],
      dtype='object')
train acc:  1.0
test acc:  0.925
[[54  2]
 [ 4 20]]
----------------------------------------
6
Index(['texture_mean', 'concave po

همانطور که می بینید بهترین عملکرد با ترکیبی از ۵ ویژگی کلیدی
 (texture_mean, concave points_mean, compactness_se, texture_worst, perimeter_worst)
  حاصل شد، که در این نقطه دقت مدل روی داده های آزمایشی به ۹۲.۵٪ رسید. پس از این مرحله اضافه کردن ویژگی‌ بیشتر هیچ بهبودی در عملکرد مدل ایجاد نکرد و تنها منجر به پیچیدگی بیشتر شد.
  با رسیدن دقت آموزش به ۱ در ادامه یادگیری مدل را تحت تاثیر قرار داد و این موضوع به دلیل حجم داده کم می تواند باعث بیش برازش شود.
  بنابراین، مدل ۵-ویژگی به عنوان مدل مناسب انتخاب می کنیم.